trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build
  displayName: '编译Debug版本'
- script: dotnet build --configuration $(buildConfiguration)
  displayName: '编译Release版本'
- script: dotnet publish -c Release
  displayName: "发布"